repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: master
    hooks:
      - id: fmt
        args: [ '--all', '--', '--check' ]
      - id: clippy
        args: [ '--', '-D', 'warnings' ]
      - id: cargo-check