version: '2.1'
services:

  postgres:
    image: postgres:14.2
    container_name: zero2prod_postgres
    ports:
      - '55432:5432'
    environment:
      POSTGRES_PASSWORD: zero2prod
      POSTGRES_USER: zero2prod
      POSTGRES_DB: zero2prod
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U zero2prod -d zero2prod" ]
      interval: 1s
      timeout: 1s
      retries: 60

  pgadmin:
    image: dpage/pgadmin4:6.7
    container_name: zero2prod_pgadmin
    ports:
      - '3333:80'
    volumes:
      - '.docker/pgadmin/servers.json:/pgadmin4/servers.json'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@slvrtrn.github.io
      PGADMIN_DEFAULT_PASSWORD: 12345
    depends_on:
      postgres:
        condition: service_healthy

  nats:
    image: 'nats:2.7.4-alpine'
    container_name: zero2prod_nats
    ports:
      - '4222:4222'
      - '8222:8222'

  nats-webui:
    image: 'sphqxe/nats-webui'
    restart: on-failure
    container_name: zero2prod_nats-webui
    ports:
      - '8080:80'